---
- name: set vars when region in key
  set_fact:
    server_name: "{{ item.value.name }}"
    server_fqdn: "{{ item.value.fqdn }}"
    server_username: "{{ item.value.username }}"
  loop: "{{ lookup('dict', server_environments) }}"
  when: "region | lower in item.key"
- name: print vars
  debug:
    msg: "Server is {{ server_name }} fqdn is {{ server_fqdn }} username is {{ server_username }}"