---
# tasks file for Roles/dansTestRole
#- name: print stuff
#  debug:
#    msg: "Region {{ item.key }} is {{ item.value.name }} ({{ item.value.fqdn}})"
#  loop: "{{ lookup('dict', server_environments) }}"
- name: set_fact when region in key
  vars:
    server_name: "{{ item.value.name }}"
    server_fqdn: "{{ item.value.fqdn }}"
    server_username: "{{ item.value.username }}"
  loop: "{{ lookup('dict', server_environments) }}"
  when: "region in item.key"
- name: print vars
  debug:
    msg: "Server is {{ server_name }} fqdn is {{ server_fqdn }} username is {{ server_username }}"