---
- hosts: labservers
  become: yes
  
  tasks:
    - name: start and enable httpd
      service:
        name: httpd
        state: stopped
        enabled: no
    - name: Delete File index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Install Apache
      yum: 
        name: httpd
        state: absent